### ISSUE TITLE
Catchable fatal error: Argument 1 passed to Prometheus\Metric::hashLabels() must be of the type array

### ISSUE THREAD

**Issue by LukasGrebe** [Lazyshot/prometheus-php#3]
Using a Gauge, im getting a notice and fatal Error:

> Notice: Undefined variable: labels in …/vendor/lazyshot/prometheus-php/src/Gauge.php on line 19
> 
> Catchable fatal error: Argument 1 passed to Prometheus\Metric::hashLabels() must be of the type array, null given, called in …/vendor/lazyshot/prometheus-php/src/Gauge.php on line 19 and defined in …/vendor/lazyshot/prometheus-php/src/Metric.php on line 76

**Comment by Lazyshot** [comment]
A proposed fix has been commit. Please update it and try again.

**Comment by LukasGrebe** [comment]
Packagist still lists the older 0.1.0 version.
Maybe see https://packagist.org/about#how-to-update-packages

A manual install works. Closed. Thank you!

**Comment by Lazyshot** [comment]
Yeah, was waiting until confirmed fix before tagging it. Should be up now.
