### ISSUE TITLE
Current counter value is always 0

### ISSUE THREAD

**Issue by croisez** [Lazyshot/prometheus-php#6]
I saw in the code that the current Counter value is stored in the Registry class.
Where are stored those Registry values?
The context is not saved. My Counter values are always 0 before inc()

**Comment by Lazyshot** [comment]
The counter object is stored in the registry class, but the value of a counter is stored within the Counter object. 

I'm not sure I follow about the context saving part. A counter should start at zero.

**Comment by michaeljs1990** [comment]
I believe they are referring to the case where you want to get the value the counter had on the last request and increment it by one.

**Comment by Lazyshot** [comment]
That persistence is entirely controlled by the prometheus push gateway. 

That is the intent of the library. To interact with the push gateway (https://github.com/prometheus/pushgateway).
